README.md
makes readme code better to look at 
adding a lang to the top tripple backtick is the difference between:
```
int yield(void);
```
and
```c
int yield(void);
```
=> add c sytax to markdown

.travis.yml
doesn't look much different, but there was one change that caught my attention for x86-64:
> Better inlining of memcpy and memset that is aware of value ranges and produces shorter alignment prologues.
=> using gcc 4.9

perf/chan.c, perf/chr.c, perf/chs.c, perf/ctxswitch.c, perf/go.c, perf/whispers.c
I ported (most of) the perf tests from libmill to libdill, just to get some rough performance status.
A few things:
- I used a deadline of `-1` everywhere. This seems unidiomatic for libdill, but better for performance? 
- No error checking, but this is how the libmill tests were.
=> Add perf tests 

cr.c, libdill.h
Some cleanups; after reading the ABI, it appears that any function call boundary will clear xmm registers.  After examining the go macro, dill_prologue and fn are both "real" calls, and thus the compiler will already mark these registers as dirty.
There is a new 32-bit implementation of context switching; currently there's some issue with clang (at least on my system).  Clang requires a larger offset within the coroutine stack.  Further investigation is required.
The new feature is dill_setsp which directly sets the stack pointer within the `go` macro.  This bypasses the stack protection mechanism provided by -fstack-protector for coroutines only (but still allowing them for non-coroutines).  This is important for newer versions of GCC.  Stack protection for the coroutine stacks is …
=> Assembly support 32-bit context switch and for x86 setting stack pointer

libdill.h
The series of patches brings compatibility between the system setjmp/longjmp implementation and the one used by libdill in x86-64 and i386 systems.
- This works with musl which does not implement pointer mangling.
- Glibc has some complex pointer mangling for security, and I do not know how to replicate it right now, but I might be able to do in the future if I investigate a bit further - but this would be relevant pre-patch work because the registers are still stored in the same order.
- Previous implementation was unnecessarily preserving rsi/rdi on x86-64, so this is faster.
- Dropped sigsetjmp and siglongjmp because we do not use them.
=> Compatible setjmp/longjmp

chan.c, handle.c
I've significantly sped up the `chsend` and `chrecv` implementations. I believe this fits in the philosophy of avoiding `choose` , for reference: [Select Statement Considered Harmful](http://250bpm.com/blog:72).
- `hquery` gets called thrice per clause in `choose`, I've implemented last-call caching in `hquery`.
- `chsend` and `chrecv` only need to call `hquery` once
- The initialisation of the clause structure fills `reserved` with zeroes causing an expensive `rep stos` on x86 architectures. Only filling in the necessary elements makes this much faster.
- `chsend` and `chrecv` can avoid setting/checking `errno` until there really is an error; setting `errno` is typically expensive.
On a i7 4770k (GCC 4.9.4), previously:
```bash
$ ./perf/chan 10
done 10M roundtrips in 1.666000 seconds …
```
=> Optimise the single-clause chsend and chrecv

cr.c, slist.h
- Minor cosmetic fix and re-add the alignment of the `struct cr`.
- Perhaps we should consider doing a per-platform check whether the stack needs to be aligned or not.  The bug only happens with `clang` because `clang` strictly follows the ABI guidelines and does not consider custom stacks.  Some versions of GCC, I believe, did also do the same thing at one point, but it introduced too many bugs so they reverted the behaviour to not assume that the stack of a function was aligned.
- Other architectures may vary, so aligning the stack is a safe choice, but may not be a necessary choice.
- It may be desired to be disabled on embedded systems where every byte counts, so maybe `#if defined (__x86_64__) || defined(__i386__)` might be a good solution.
=> Add 16-byte alignment of client stack and comment

man/Makefile.am
`%.3: %.md` accessible only for GNU make. This is the only GNU-specific thing which does not allow to use BSD make, everything else handled by automake. Portable `.md.3` is enough in this case.
=> Use portable version of make suffixes

kqueue.c.inc, kqueue.h.inc, pollset.c, pollset.h
This patch is licensed under X11/MIT.
I removed `BSD` because it doesn't seem to be defined in FreeBSD anyway, and I guess other BSDs will be explicitly enumerated when someone will verify library there.
Or I can also add `__NetBSD__` and `__OpenBSD__` hoping it will work there too.
=> Use __FreeBSD__ to detect BSD

cr.c
I restructured the code so that `dill_longjmp` appears at the end of the function body.
EDIT: the comments may need rewording.
=> Fix bad stack unwinding inside dill_wait

cr.c
fixes warning on osx: `control may reach end of non-void function [-Wreturn-type]`
=> fix clang warning -Wreturn-type

.gitignore, build_options.html, build_options.md, compatibility.html, compatibility.md, gendocs, index.html, index.md, structured-concurrency.html, structured-concurrency.md, threads.html, threads.md, tutorial.html, tutorial.md
Grammar fixes in tutorial.md in reference to #58 
Also a faster gendocs scripts (ditch it if you don't like it).
=> Grammar fixes in tutorial.md

man/chdone.md, man/chmake.md, man/chmake_mem.md, man/choose.md, man/chrecv.md, man/chsend.md, man/fdclean.md, man/fdin.md, man/fdout.md, man/go.md, man/go_mem.md, man/hclose.md, man/hdup.md, man/hmake.md, man/hquery.md, man/msleep.md, man/now.md, man/yield.md
- Changed the formatting to make the manpages look like other POSIX manpages
on Linux  (bold constant names, bold synopses, underlined variable names).
- Fixed a few grammar errors.
- Dropped word wrapping out of the few outliers that had it
(I figured it was best left to manpage browsers).
=> Edit manpages

libdill.c, utils.h
Try this:
- There's 100us delay for the first `now()` call to measure `rdtsc`
- Performance is similar to using POSIX timers - `go` bench is 2-3 ns faster, `ctxswitch` is 2-3 ns slower.
=> rdtsc now()

Makefile.am, perf/timer.c
Preliminary take on benchmarking the internal timer implementation.
It uses coroutines and `msleep`.  Launching too many coroutines does not work with the page guard -- so disable it by building libdill with -DDILL_NOGUARD.
`./perf/timer 100000`
=> Add timer perf benchmark

ipaddr.c
This change breaks the tight loop when name is unresolvable.
Example code:
```
#include <libdill.h>
#include <dsock.h>
#include <assert.h>
#include <stdio.h>
int main() {
ipaddr addr;
int rc = ipaddr_remote(&addr, "nonexistent.com", 80, 3, now() + 1000);
char buf[255];
printf("%d: [%s]\n", rc, ipaddr_str(&addr, buf));
}
```
In practice, I've seen rc == `DNS_ENONAME` and `DNS_EFAIL`. Without this patch, the code goes into an infinite tight loop.
=> Update DNS processing in ipaddr.c

tutorial/protocol/step1.c, tutorial/protocol/step2.c, tutorial/protocol/step3.c, tutorial/protocol/step4.c, tutorial/protocol/step5.c, tutorial/protocol/step6.c, tutorial/protocol/step7.c
Looks like just a typo to me.
GCC warns about this btw:
```
warning: unused variable ‘err’ [-Wunused-variable]
if(h < 0) {int err = errno; goto error2;}
^
warning: ‘err’ may be used uninitialized in this function [-Wmaybe-uninitialized]
errno = err;
```
License: X11/MIT
=> Fix not storing the returned error code correctly

configure.ac, dns/dns.c, ipaddr.c
Otherwise e.g. valgrind complains.
=> FreeBSD requires sin_len field to be set.

tests/ipaddr.c
AF_INET is not defined on FreeBSD without `<sys/socket.h>`.
=> compile on freebsd

ipaddr.c
If resolv.conf if not available, don't crash the whole program.
=> Avoid failing hard in case of DNS configuration failure

ipaddr.c, tests/ipaddr.c
When using non-local DNS resolver, large replies over TCP will break the existing code.
We need to be able to wait for the events to go out (POLLOUT), not just wait for the POLLIN. That's when we use a TCP fall-back.
Make sure your /etc/resolv.conf points to a non-local DNS resolver.
Attempt to ipaddr_remote("large-dns-response-4k.lionet.info").
=> Long dns names

epoll.c.inc
Hi, when using the 'fdin' or 'fdout' libdill functions, Valgrind kept complaining about unitialized bytes in the epoll_ctl syscall, so here's a quick patch to shut it up when the --enable-valgrind flag is set. Hope it helps!
=> Valgrind unitialized bytes warning fix for dill_pollset_poll

ctx.c
CC       libdill_la-ctx.lo
ctx.c:72:12: warning: implicit declaration of function 'pthread_main_np' is
invalid in C99 [-Wimplicit-function-declaration]
return pthread_main_np();
^
1 warning generated.
=> Include pthread_np.h on OpenBSD for pthread_main_np.

tls.c
This is a patch to skip the condition of trying to write a zero length iolist via SSL_write ( Issue #161 )
=> don't write 0 bytes via SSL_write (as behavior is undefined in OpenSSL)

http.c
dill_http_attach allocates memory with obj = malloc(), however the logic was reversed in dill_http_hclose such that allocated memory would not be freed (or worse still, if dill_http_attach_mem was called to attach then on dill_http_hclose free would be called referencing memory that had not been allocated).
=> fix free() logic in dill_http_hclose(), only free if malloc'd

dns/dns.c
I've ran into a problem on Ubuntu 18 where DNS isn't working correctly. The behavior is seen as:
$ ./tutorial/sockets/step4 http libdill.org /index.html
Cannot resolve server address: Cannot assign requested address
$
I tracked this down to the following statement in dns_ai_setent()... 
saddr	= memset(&sin, '\0', sizeof sin);
what appears to be happening is that the compiler is optimizing out this statement such that saddr != &sin after this statement. The result is that dill_ipaddr_remote() is calling dns_ai_nextent() and the value returned int &it isn't the right data (because it was copied to saddr, which != &sin)
The patch replaces this one statement with two such that if the memset call is optimized away then saadr is still set to the correct address. Incidentally, compiling with …
=> avoid issue with memset (optimizer issue with builtin_memset?)

tests/socks5.c
I've replaced the external lookup with a lookup of "localhost" and expanded the test cases in a loop.
=> remove external dependecies (lookup of libdill.org) from socks5 test

website/src/tutorial-basics.md, website/tutorial-basics.html
Hey,
I've been reading through the basics tutorial and found some typos.
Here is a pull request with fixes, if you're willing to accept them :slightly_smiling_face: 
Best regards,
Rok
=> Tutorial typo fix

dns/dns.h
The PR is supposed to address the issue https://github.com/sustrik/libdill/issues/191
Tested with:
```
> gcc --version
gcc (GCC) 9.1.0
```
=> Fix compilation for gcc 9.1.0

libdill.h
The "opaque but sized" structures (dill_*_storage) may cause data (in particular pointers) not to be aligned. This is not a problem in x86_64, but in ARM it causes loads and stores to be unpredictable (i.e. store wrong data). Then the code will try to invoke a function from a wrong pointer and jumps to nowhere, causing a segfault.
The `struct dill_suffix_storage suffix_mem;` member in dill_http_sock is not aligned. Thus, the `dill_hvfs` in the suffix socket is not aligned either. `dill_suffix_attach_mem` will try to set `self->hvfs.query` and `close` but because these words are not aligned, the pointers have garbage written (and read). Then `dill_hquery` will try to invoke this pointers and jump to nowhere.
The size increase caused by alignment is compensated by the smaller pointer sizes …
=> Force alignment in ARM architectures

http.c, iol.c, prefix.c, socks5.c, term.c, tls.c
These are minor alterations. Some variable initialization and some that appear to be copy paste errors.
I was using the Xcode build system which was complaining about these.
=> Variable initialization and apparent copy/paste error removed.

CMakeLists.txt, configure.ac, ctx.c, ctx.h, libdill.h
Similar to #120, looks like `--disable-sockets` is broken since 7e663dd467.
```
alex@aineko:~/src/libdill$ ./configure --enable-debug --disable-shared --disable-sockets --disable-tls
alex@aineko:~/src/libdill$ make V=1
[snipped]
gcc -DPACKAGE_NAME=\"libdill\" -DPACKAGE_TARNAME=\"libdill\" -DPACKAGE_VERSION=\"Unknown\" -DPACKAGE_STRING=\"libdill\ Unknown\" -DPACKAGE_BUGREPORT=\"sustrik@250bpm.com\" -DPACKAGE_URL=\"http://libdill.org/\" -DPACKAGE=\"libdill\" -DVERSION=\"Unknown\" -DDILL_THREADS=1 -DDILL_PTHREAD=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_MPROTECT=1 -DHAVE_LIBRT=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_EPOLL_CREATE=1 -DHAVE_EPOLL=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 …
```
=> fix --disable-sockets

configure.ac
Retrieve openssl dependencies through pkg-config to fix the following static build failure:
```
checking for SSL_ctrl  in -lssl... no
configure: error: libssl not found; install OpenSSL
```
Fixes:
- http://autobuild.buildroot.org/results/d3bbbdb8433f1da69304a42bc3f3d4a49ce52931
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix ssl static build
